### ISSUE TITLE
Persist word count

### ISSUE THREAD

**Issue by paoloambrosio-skyuk** [paoloambrosio-skyuk/confcloud#2]
Word count should be persisted into a database of some sort, so that we don't lose it if the application goes down.

**Comment by paoloambrosio-skyuk** [comment]
Possibly we should be able to know when each vote was cast, so that we can replay the sequence at a later time (like a time-lapse of how the cloud has changed from beginning to end)... if not, create another card for this to track it.

**Comment by matthedude** [comment]
I've done a very simple start to this using a persistent actor. The time lapse sounds like a good idea - the events are stored in order so shouldn't be too hard to hook up.

**Comment by paoloambrosio-skyuk** [comment]
Closed by #8
