### ISSUE TITLE
Write tests (if it's going to be reused)

### ISSUE THREAD

**Issue by paoloambrosio-skyuk** [paoloambrosio-skyuk/confcloud#6]
This project was started as an experiment on Scala.JS, so it has no tests whatsoever. No point writing them if it's going to be a one-off.

**Comment by paoloambrosio-skyuk** [comment]
Let's close it for now and re-open it if needed.

**Comment by matthedude** [comment]
I have kept in this spirit with my experiments with akka Persistence and Play!
